version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install boto3

  pre_build:
    commands:
      - echo Pre-build started...

  build:
    commands:
      - echo Build started...
      - python etl_script.py

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
